### ISSUE TITLE
lab

### ISSUE THREAD

**Issue by Saint-Hawks** [codedamn/codedamn#17]
in c++ lab test the automated samples are not working but the user samples are working fine

**Comment by Pranavtechie** [comment]
Hello @Saint-Hawks , can you share the link to the lab here

**Comment by Saint-Hawks** [comment]
> 

https://codedamn.com/learn/cpp-language/c-syntax-and-structure/basic-variable-operattions.PdydzZSsHQnqVRQ20_5o_

**Comment by Pranavtechie** [comment]
Hello @Saint-Hawks , we have taken down non-functional labs and will bring them back up once they are working as expected
